version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      pip-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      pip-production:
        dependency-type: production
        update-types:
          - patch
