[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[tool.mypy]
strict = true

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and pycodestyle (`E`) codes by default.
# Enable isort (`I`) for sorted imports
select = ["ALL"]
ignore = [
    "D203",   # `one-blank-line-before-class` - conflicts with D211 `no-blank-line-before-class`
    "D205",   # `blank-line-after-summary` - not creating multiline docstrings with extra descriptions
    "D213",   # `multi-line-summary-second-line` - conflicts with D212 `multi-line-summary-first-line`
    "COM812", # `missing-trailing-comma` - avoids warning about this potentially causing conflicts when used with the formatter
    "ISC001"  # `single-line-implicit-string-concatenation` - avoids warning about this potentially causing conflicts when used with the formatter
    ]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
# Ignore certain errors for cookiecutter hooks
# INP001: "_ is part of an implicit namespace package. Add an `__init__.py`" - Not needed for cookiecutter hooks
# T201: "`print` found" - We want to print things when generating the project
# S603: "`subprocess` call: check for execution of untrusted input" - Seem to be false positives (see https://github.com/astral-sh/ruff/issues/4045)
# S607: "Starting a process with a partial executable path" - We don't know/care where post-gen tools like xcodegen, git, etc. are installed on the user's system
"hooks/**.py" = ["INP001", "T201", "S603", "S607"]

# Ignore errors in test module
# D104: "Missing docstring in public package" - No need to have it for the tests
# TODO: Maybe we relax docstring requirements on tests in general? (probably no need for argument/parameter/return descriptions)
"tests/__init__.py" = ["D104"]

# S101: "Use of `assert` detected" - Asserts are needed for tests
"tests/**.py" = ["S101"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
