name: Test

on: [push, workflow_dispatch]

concurrency:
  # Cancel any in-progress runs for this workflow/branch combination
  #{% raw %}
  group: ${{ github.workflow }}-${{ github.ref }}
  #{% endraw %}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Run tests
        run: bash run-tests.sh
