name: Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  # Cancel any in-progress runs for this workflow/branch combination
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Set up ruby environment
        uses: ruby/setup-ruby@v1
        with:
          # Automatically runs `bundle install` and caches the result
          bundler-cache: true

      - name: Run tests
        run: ./run-tests.sh
