name: Deploy

on:
  workflow_run:
    workflows: [Test]
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
  check-for-changes:
    name: Check for template changes
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      actions: write # Needed so that the workflow run can be cancelled if necessary
    outputs:
      template-files-changed: ${{ steps.check-for-changes.outputs.template-files-changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Get commit of last successful deployment
        id: last-successful-commit
        uses: tylermilner/last-successful-commit-hash-action@v1
        with:
          github-token: ${{ github.token }}
          workflow-id: deploy.yml
          branch: main

      - name: Check for changes in the template directory
        uses: dorny/paths-filter@v3
        id: check-for-changes
        with:
          base: ${{ steps.last-successful-commit.outputs.commit-hash }}
          filters: |
            template-files-changed:
              - '{{ cookiecutter.project_root }}/**'

      - name: Show check for changes result
        run: |
          echo "Template files changed: ${{ steps.check-for-changes.outputs.template-files-changed }}"

      - name: Cancel deployment if no changes
        id: cancel-if-necessary
        if: ${{ steps.check-for-changes.outputs.template-files-changed == 'false' }}
        run: |
          echo "No changes detected in template directory. Cancelling workflow run."
          gh run cancel ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ github.token }}

  deploy-generated-template:
    name: Deploy generated template
    runs-on: ubuntu-22.04
    needs: [check-for-changes]
    if: ${{ needs.check-for-changes.outputs.template-files-changed == 'true' }}
    steps:
      - name: Checkout output repository
        uses: actions/checkout@v4
        with:
          repository: 'tylermilner/cookiecutter-ios-swiftui-output'
          ref: 'main'
          token:  ${{ secrets.TEMPLATE_OUTPUT_REPO_TOKEN }}

      - name: Get run ID of "Test" workflow
        id: get-run-id
        run: |
          OTHER_REPO="tylermilner/cookiecutter-ios-swiftui"
          WF_NAME="Test"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download artifact from "Test" workflow
        uses: actions/download-artifact@v4
        with:
          name: template-output # Match name used in test.yml upload artifact step
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}

      - name: Show downloaded files
        run: ls -la

      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"

      - name: Commit and push generated template
        run: |
          export COMMIT_MESSAGE="Generated template from ${{ github.repository }}/${{ github.ref}}@${{ github.sha }}"
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push
