name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version
        cache: pipenv

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    # - name: Cache Pipenv dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.local/share/virtualenvs
    #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pipenv-

    - name: Run tests
      run: pipenv run pytest
