name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Set up Python, including cache for pipenv virtual environment
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version
        cache: pipenv

    - name: Install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv

    - name: Install project dependencies
      run: pipenv install --dev

    - name: Run tests
      run: pipenv run pytest
