name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Set up Python, including cache for pipenv virtual environment
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version
        cache: pipenv

    - name: Install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv

    - name: Install project dependencies
      run: pipenv install --dev

    - name: Run tests
      run: pipenv run pytest

    - name: Generate template from defaults
      run: ./generate-default-project.sh

    - name: Upload generated template
      uses: actions/upload-artifact@v4
      id: upload-generated-template
      with:
        name: template-output
        path: my-app
  
  deploy:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'tylermilner/cookiecutter-ios-swiftui-output'
          ref: 'main'
          token:  ${{ secrets.TEMPLATE_OUTPUT_REPO_TOKEN }}

      - name: Print current directory
        run: pwd

      - name: Print GITHUB_WORKSPACE directory
        run: echo $GITHUB_WORKSPACE

      - name: List current files
        run: ls -la

      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"

      - name: Download generated template
        uses: actions/download-artifact@v4
        with:
          name: template-output

      - name: List downloaded files
        run: ls -la

      - name: Commit and push generated template
        run: |
          export COMMIT_MESSAGE="Generated template from ${{ github.repository }}/${{ github.ref}}@${{ github.sha }}"
          echo "Commit message: $COMMIT_MESSAGE"
      