name: Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  # Match path used in `make generate` command
  GENERATED_TEMPLATE_DIR: my-app

permissions:
  contents: read

concurrency:
  # Cancel any in-progress runs for this workflow/branch combination
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Set up Python, including cache for pipenv virtual environment
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: pipenv

      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv

      - name: Install project dependencies
        run: pipenv install --dev

      - name: Run mypy
        run: pipenv run mypy .

      - name: Check Format
        run: pipenv run ruff format

      - name: Lint
        run: pipenv run ruff check

      - name: Run tests
        run: pipenv run pytest

      - name: Generate template from defaults
        run: make generate

      - name: List generated files
        run: ls -la ${{ env.GENERATED_TEMPLATE_DIR}}

      - name: Upload generated template
        uses: actions/upload-artifact@v4
        id: upload-generated-template
        with:
          # Match name used in deploy.yml download artifact step
          name: template-output
          path: ${{ env.GENERATED_TEMPLATE_DIR}}
          include-hidden-files: true
